name: atest
favicon: null
layout_spectrum: 0.9872532191220671
typography_spectrum: 0.17471055989153683
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5295707357581705
  lightness: 0.6305148156825453
  saturation: 0.4280561520718038
  rhythmicContrast: 0.021344749024137855
purpose: []
